// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrAlNFmIcZ-c5_haDnQ8V0W-lI0sljh0',
    appId: '1:1009150970690:android:d855c7c556ed11393fd6db',
    messagingSenderId: '1009150970690',
    projectId: 'calisthenics-app-6d03f',
    databaseURL: 'https://calisthenics-app-6d03f-default-rtdb.firebaseio.com',
    storageBucket: 'calisthenics-app-6d03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNVAa4CE0co6ssiY7GhCZzjRnpB20h-g',
    appId: '1:1009150970690:ios:13bc2c339b11ada73fd6db',
    messagingSenderId: '1009150970690',
    projectId: 'calisthenics-app-6d03f',
    databaseURL: 'https://calisthenics-app-6d03f-default-rtdb.firebaseio.com',
    storageBucket: 'calisthenics-app-6d03f.appspot.com',
    iosClientId: '1009150970690-7hr7tt3if5680gkb38t3bpaojcf7iov3.apps.googleusercontent.com',
    iosBundleId: 'com.example.calisthenicsApp',
  );
}
